version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: typing
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./tmp/mysqld:/var/run/mysqld
  web:
    container_name: node
    build: .
    ports:
      - "8080:3000"
    tty: true
    depends_on:
      - db
    volumes:
      - ./myapp :/myapp
